import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.JTable;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Stefano Casti
 */
public class Finestra2 extends javax.swing.JFrame {
    private Magazzino magazzino;
    
    

    /**
     * Creates new form Finestra2
     */
    public Finestra2(Magazzino magazzino) {
        initComponents();
        this.magazzino = magazzino;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        casellaNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        casellaCodice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        casellaDescrizione = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        casellaGiacenza = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        casellaPrezzo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        AggiungiButton = new javax.swing.JButton();
        EliminaButton = new javax.swing.JButton();
        ModificaButton = new javax.swing.JButton();
        VisualizzaButton = new javax.swing.JButton();
        VisualizzaTuttiButton = new javax.swing.JButton();
        SalvaButton = new javax.swing.JButton();
        CaricaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel1.setText("NOME PRODOTTO");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel2.setText("CODICE PRODOTTO");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel3.setText("DESCRIZIONE PRODOTTO");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel4.setText("GIACENZA PRODOTTO");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel5.setText("PREZZO PRODOTTO");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codice", "Nome", "Descrizione", "Giacenza", "Prezzo"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PROGRAMMA GESTIONALE MAGAZZINO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(1163, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(547, 547, 547))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 920));

        AggiungiButton.setBackground(new java.awt.Color(0, 204, 204));
        AggiungiButton.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        AggiungiButton.setForeground(new java.awt.Color(255, 255, 255));
        AggiungiButton.setText("AGGIUNGI PRODOTTO");
        AggiungiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AggiungiButtonActionPerformed(evt);
            }
        });

        EliminaButton.setBackground(new java.awt.Color(0, 204, 204));
        EliminaButton.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        EliminaButton.setForeground(new java.awt.Color(255, 255, 255));
        EliminaButton.setText("ELIMINA PRODOTTO");
        EliminaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminaButtonActionPerformed(evt);
            }
        });

        ModificaButton.setBackground(new java.awt.Color(0, 204, 204));
        ModificaButton.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        ModificaButton.setForeground(new java.awt.Color(255, 255, 255));
        ModificaButton.setText("MODIFICA PRODOTTO");
        ModificaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificaButtonActionPerformed(evt);
            }
        });

        VisualizzaButton.setBackground(new java.awt.Color(0, 204, 204));
        VisualizzaButton.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        VisualizzaButton.setForeground(new java.awt.Color(255, 255, 255));
        VisualizzaButton.setText("VISUALIZZA PRODOTTO");
        VisualizzaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizzaButtonActionPerformed(evt);
            }
        });

        VisualizzaTuttiButton.setBackground(new java.awt.Color(0, 204, 204));
        VisualizzaTuttiButton.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        VisualizzaTuttiButton.setForeground(new java.awt.Color(255, 255, 255));
        VisualizzaTuttiButton.setText("VISUALIZZA TUTTI PRODOTTI");
        VisualizzaTuttiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizzaTuttiButtonActionPerformed(evt);
            }
        });

        SalvaButton.setBackground(new java.awt.Color(0, 204, 204));
        SalvaButton.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        SalvaButton.setForeground(new java.awt.Color(255, 255, 255));
        SalvaButton.setText("SALVA");
        SalvaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvaButtonActionPerformed(evt);
            }
        });

        CaricaButton.setBackground(new java.awt.Color(0, 204, 204));
        CaricaButton.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        CaricaButton.setForeground(new java.awt.Color(255, 255, 255));
        CaricaButton.setText("CARICA");
        CaricaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaricaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EliminaButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ModificaButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(VisualizzaButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(VisualizzaTuttiButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AggiungiButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(SalvaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CaricaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(AggiungiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(EliminaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(ModificaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(VisualizzaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(VisualizzaTuttiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SalvaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CaricaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(773, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(casellaDescrizione, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casellaGiacenza, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casellaPrezzo, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casellaCodice, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casellaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1570, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(casellaCodice, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(casellaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(casellaDescrizione, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(casellaGiacenza, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(casellaPrezzo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AggiungiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AggiungiButtonActionPerformed
        String C = casellaCodice.getText();
        String N = casellaNome.getText();
        String D = casellaDescrizione.getText();
        String G = casellaGiacenza.getText();
        String P = casellaPrezzo.getText();

        if (C.isEmpty() || N.isEmpty() ||  D.isEmpty() || G.isEmpty() || P.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Riempi tutte le caselle", "Errore", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int G1 = Integer.parseInt(G);
        double P1 = Double.parseDouble(P);

        if (contieneProdottoConCodice(C)) {
        JOptionPane.showMessageDialog(null, "Prodotto già esistente con questo codice", "Errore", JOptionPane.ERROR_MESSAGE);
        return;
    }
        Prodotto p = new Prodotto(C, N, D, G1, P1);
        try {
            magazzino.AggiungiProdotto(p);
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            Object[] row = {C, N, D, G1, P1};
            model.addRow(row);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, "Prodotto già esistente con questo codice", "Errore", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_AggiungiButtonActionPerformed
    private boolean contieneProdottoConCodice(String codice) {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    for (int row = 0; row < model.getRowCount(); row++) {
        Object valoreCella = model.getValueAt(row, 0);
        if (valoreCella != null && valoreCella.toString().equals(codice)) { 
            return true;
        }
    }
    return false;
}
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        int rigaSelezionata = jTable1.getSelectedRow();
        casellaCodice.setText(model.getValueAt(rigaSelezionata, 0).toString());
        casellaNome.setText(model.getValueAt(rigaSelezionata, 1).toString());
        casellaDescrizione.setText(model.getValueAt(rigaSelezionata, 2).toString());
        casellaGiacenza.setText(model.getValueAt(rigaSelezionata, 3).toString());
        casellaPrezzo.setText(model.getValueAt(rigaSelezionata, 4).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void ModificaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificaButtonActionPerformed
        int i = jTable1.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if (i >= 0) {
            String codiceDaModificare = (String) model.getValueAt(i, 0);
            model.setValueAt(casellaNome.getText(), i, 1);
            model.setValueAt(casellaDescrizione.getText(), i, 2);
            model.setValueAt(casellaGiacenza.getText(), i, 3);
            model.setValueAt(casellaPrezzo.getText(), i, 4);

        String nuovoNome = casellaNome.getText();
        String nuovaDescrizione = casellaDescrizione.getText();
        int nuovaGiacenza = Integer.parseInt(casellaGiacenza.getText());
        double nuovoPrezzo = Double.parseDouble(casellaPrezzo.getText());

        magazzino.ModificaProdotto(codiceDaModificare, nuovoNome, nuovaDescrizione, nuovaGiacenza, nuovoPrezzo);
        } else {
            JOptionPane.showMessageDialog(null, "Nessun prodotto selezionato");
        }
    }//GEN-LAST:event_ModificaButtonActionPerformed

    private void EliminaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminaButtonActionPerformed
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        int rigaSelezionata = jTable1.getSelectedRow();
        if(rigaSelezionata >= 0){
            String codice = (String) model.getValueAt(rigaSelezionata, 0);
            model.removeRow(rigaSelezionata);
            magazzino.EliminaProdotto(codice);
        }
        else{
            JOptionPane.showMessageDialog(null, "Nessun prodotto selezionato");
        }        
    }//GEN-LAST:event_EliminaButtonActionPerformed

    private void VisualizzaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizzaButtonActionPerformed
        String codice = JOptionPane.showInputDialog("Inserisci il codice del prodotto da visualizzare:");
        
        if (codice != null && !codice.isEmpty()) {
            magazzino.VisualizzaProdotto(codice);
        } else {
            JOptionPane.showMessageDialog(null, "Inserisci un codice valido");
        } 
    }//GEN-LAST:event_VisualizzaButtonActionPerformed

    private void VisualizzaTuttiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizzaTuttiButtonActionPerformed
        magazzino.VisualizzaTuttiProdotti();
    }//GEN-LAST:event_VisualizzaTuttiButtonActionPerformed

    private void SalvaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvaButtonActionPerformed
        try {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Nessun dato da salvare", "Errore", JOptionPane.ERROR_MESSAGE);
            return;
        }

        BufferedWriter bw = new BufferedWriter(new FileWriter("dati_tabella.txt"));

        for (int row = 0; row < model.getRowCount(); row++) {
            for (int col = 0; col < model.getColumnCount(); col++) {
                bw.write(model.getValueAt(row, col).toString());
                bw.write("\t");
            }
            bw.newLine();
        }

        bw.close();

        JOptionPane.showMessageDialog(null, "Dati salvati con successo", "Salvataggio", JOptionPane.INFORMATION_MESSAGE);
    } catch (IOException e) {
        JOptionPane.showMessageDialog(null, "Errore durante il salvataggio dei dati", "Errore", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_SalvaButtonActionPerformed
    }
    private void importaDaFile(File file) throws IOException {
        try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Pulisci la tabella prima di importare

        String line;
        while ((line = reader.readLine()) != null) {
            String[] data = line.split("\\t");

            if (data.length >= 5) {
                String codice = data[0];
                String nome = data[1];
                String descrizione = data[2];
                int giacenza = Integer.parseInt(data[3]);
                double prezzo = Double.parseDouble(data[4]);

                Prodotto prodotto = new Prodotto(codice, nome, descrizione, giacenza, prezzo);
                
                // Aggiunge l'oggetto Prodotto alla lista
                try {
                    magazzino.AggiungiProdotto(prodotto);
                } catch (IllegalArgumentException e) {
                    System.out.println(e.getMessage());
                }

                // Aggiunge la riga alla tabella
                model.addRow(data);
            }
        }
    }
    }
    
    private void CaricaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaricaButtonActionPerformed
        try {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Seleziona il file da cui importare");

        int userSelection = fileChooser.showOpenDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            importaDaFile(selectedFile);
            JOptionPane.showMessageDialog(null, "Dati importati con successo", "Importazione", JOptionPane.INFORMATION_MESSAGE);
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(null, "Errore durante l'importazione dei dati", "Errore", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace(); 
    }
    }//GEN-LAST:event_CaricaButtonActionPerformed

        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Finestra2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Finestra2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Finestra2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Finestra2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Magazzino magazzino = new Magazzino();
                new Finestra2(magazzino).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AggiungiButton;
    private javax.swing.JButton CaricaButton;
    private javax.swing.JButton EliminaButton;
    private javax.swing.JButton ModificaButton;
    private javax.swing.JButton SalvaButton;
    private javax.swing.JButton VisualizzaButton;
    private javax.swing.JButton VisualizzaTuttiButton;
    private javax.swing.JTextField casellaCodice;
    private javax.swing.JTextField casellaDescrizione;
    private javax.swing.JTextField casellaGiacenza;
    private javax.swing.JTextField casellaNome;
    private javax.swing.JTextField casellaPrezzo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    
}


